name: Hello World!

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Run date
        run: date
      - name: Run ls -l
        run: ls -l
      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Warn
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Test warning.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Error
    uses: rjstone/discord-webhook-notify@v1
    with:
        severity: error
        details: Test error.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}